import {
  AlertTriangle,
  Apple,
  Ban,
  Bed,
  Bike,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  Clock3,
  ClipboardList,
  Dumbbell,
  Flame,
  Footprints,
  GlassWater,
  Leaf,
  Lightbulb,
  Mail,
  Moon,
  PersonStanding,
  Pizza,
  Salad,
  Sandwich,
  Soup,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Trophy,
  User,
  Utensils,
  Wind,
  type LucideIcon,
} from "lucide-react";

interface Props {
  emoji: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

const ICON_MAP: Record<string, LucideIcon> = {
  "🔥": Flame,
  "🍽️": Utensils,
  "✅": CircleCheck,
  "🏆": Trophy,
  "👤": User,
  "📬": Mail,
  "🌱": Leaf,
  "🌙": Moon,
  "🚫": Ban,
  "💡": Lightbulb,
  "🕘": Clock3,
  "⚠️": AlertTriangle,
  "🚶": Footprints,
  "🏃": PersonStanding,
  "🚴": Bike,
  "🏋️": Dumbbell,
  "💪": Dumbbell,
  "🌬️": Wind,
  "📵": Ban,
  "😴": Bed,
  "💧": GlassWater,
  "🍎": Apple,
  "🥤": Utensils,
  "⏸️": Circle,
  "⏳": Clock3,
  "🌅": Sunrise,
  "☀️": Sun,
  "👟": Footprints,
  "🎉": Sparkles,
  "📋": ClipboardList,
  "📊": CircleDot,
  "😋": CircleCheck,
  "😰": CircleAlert,
  "🍫": Utensils,
  "🍔": Utensils,
  "🍟": Utensils,
  "🌭": Utensils,
  "🍗": Utensils,
  "🥪": Sandwich,
  "🍕": Pizza,
  "🥖": Sandwich,
  "🍚": Utensils,
  "🍛": Utensils,
  "🫓": Sandwich,
  "🥞": Utensils,
  "🔺": AlertTriangle,
  "🍲": Soup,
  "🍞": Sandwich,
  "🍳": Utensils,
  "🍜": Soup,
  "🥡": Utensils,
  "🥟": Utensils,
  "🥛": GlassWater,
  "🍵": Utensils,
  "🧃": GlassWater,
  "🥔": Utensils,
  "🍦": Utensils,
  "🍮": Utensils,
  "🥗": Salad,
  "🍱": Utensils,
  "🟡": CircleDot,
  "🟠": CircleDot,
  "🔴": CircleDot,
  "💀": AlertTriangle,
  "💤": Bed,
  "⭐": Star,
  "✨": Sparkles,
  "🧘": PersonStanding,
  "🦵": Footprints,
  trophy: Trophy,
  flame: Flame,
  strength: Dumbbell,
  star: Star,
  sparkles: Sparkles,
  success: CircleCheck,
  "warning-low": CircleDot,
  "warning-mid": CircleDot,
  "warning-high": CircleAlert,
};

export function EmojiIcon({ emoji, size = 18, className, strokeWidth = 2.2 }: Props) {
  const Icon = ICON_MAP[emoji] ?? Sparkles;
  return <Icon aria-hidden size={size} strokeWidth={strokeWidth} className={className} />;
}
